### ISSUE TITLE
County data

### ISSUE THREAD

**Issue by m6tlik** [koroonakaart/koroonakaart#82] opened 2020-04-01 11:17 UTC
Is all correct that in country data the number registred cases has declined?

And, is it possible to change the colour palette for /10k map into log-scale that Saaremaa outlier would not dominate.

**Comment by keeganmcbride** [comment] 2020-04-02 17:25
The first issue was caused by the whole data problems caused by Terviseamet, should be gone now.

Re second issue, we had adjusted the coloring and it should be fixed now.

**Closed as completed by keeganmcbride** 2020-04-02 17:25 UTC
