### ISSUE TITLE
Show possible number of infected

### ISSUE THREAD

**Issue by veikod** [koroonakaart/koroonakaart#24] opened 2020-03-18 13:37 UTC
Use the following equation to show the amount of people who are infected:
Th=2^(P/d)*Tj, where
Th - possible number of infected
P - incubation period
d - doubling rate
Tj - tested positive/current amount of known infected ones

Also show difference of prognoses and actual data.

**Comment by neuroactive** [comment] 2020-03-18 20:00
Hi, thanks for the suggestion. We are definitely looking into whether we should display estimates of the number of infected people. This could help to communicate to the public a more realistic view of the prevalence of the disease.

We need to proceed with caution, however, as we don't want to publish information which could potentially endanger people, for example by predicting a low number of infected people in an area which actually has significant levels of infection (perhaps caused by a lack of testing in that area, for example). A prediction for total number of infected people in the country is less problematic in this regard.

**Comment by veikod** [comment] 2020-03-18 20:41
It depends on the values used to calculate the possible number of infected people. For example, if doubling rate is 3 days and incubation period is 14 days, then if amount of people tested positive is 258, the possible number of infected people is equal to 6552. That is the number of infected we should see after an incubation period is over (then again, if testing is adequate).

**Comment by neuroactive** [comment] 2020-03-18 21:03
Those who are being tested at the moment aren't drawn from a representative sample of the population. Individuals in high risk groups are being prioritised due to limited testing capacity. Presumably that would affect this kind of model then?

**Comment by veikod** [comment] 2020-03-18 21:30
Definitely, it is showing the lower rate than it should be. For example, my own model predicts that currently there should be 538 positive cases, if tested properly (that is, cases outside of incubation period). In my model I took the known case amount from the period when testing was done for everybody with symptoms, inserted that number into the model and added the incubation period. Outcome is the amount of currently expected positive cases (538). Note that this is not the amount of infected, that my model predicts is in between 6000-13000 (depends on the values for incubation period and effective doubling rate).

**Comment by keeganmcbride** [comment] 2020-03-18 21:38
This is something we will have to discuss and debate a bit internally as the main goal has to be displaying only accurate information that we have. While I agree forecasting and prediction is highly important, it may be a bit out of scope for the application in its current form. Once I talk a bit more with Terviseamet we can decide how to proceed with this.

**Comment by jaanus** [comment] 2020-03-21 05:54
As a regular user, I would find the ”possible” cases unnecessary and outside the scope of this project. Sure, there are more infected than are tested. But it’s good to have this project focused on tested/sick cases. Instead of predictions and estimates, I’d ask for things like length of hospital stay, number and occupancy of beds/ICU units/ventilators and such.

**Comment by kunstnik** [comment] 2020-03-27 08:29
Agree, let's stay on the solid base of facts. Future models may be made in close cooperation with epidemic statisticians and shown on a different page for a different audience.

Nevertheless the pain of predictability of the nearest future, to make plans is important for everyone. As POSSIBLE number in current issue #24 could indicate. 
Suggestion (solving problem, described in issue #60): to gather data about main corona symptoms (like cough, fever and shortness of breath; source: https://www.cdc.gov/coronavirus/2019-ncov/about/symptoms.html, maybe also bloody nose, pain in the chest, loss of taste and smell or diarrhea; full choice of symptoms: https://jamanetwork.com/journals/jama/fullarticle/2761044?guestAccessKey=f61bd430-07d8-4b86-a749-bec05bfffb65 ) on grassroot level, for example via Facebook. The formula should contain data about representativity (Facebook users per general population). 
Agree, this isn't correct data, because self-diagnosed, but IT IS REAL-TIME data. In current situation of social distancing this could be more valuable, than accuracy. (also tests can fail sometimes - it's is not 100% accurate data either) 
The appropriate color, to indicate this inaccuracy, would be light green (somewhat ill/semidiagnosed) in Color Legend, proposed in issue #51.

**Comment by kunstnik** [comment] 2020-03-27 08:44
Something funny also: to start and spread self-diagnosing tool rapidly, I'd suggest to use existing FB emoticons on a special self-diagnosing group. See, how animated emoticons fit to symptoms 😁:
![sketch-1584612478709](https://user-images.githubusercontent.com/62639296/77738083-db0f6780-7017-11ea-9976-9586b39b72e6.png)
In English: 👍 Recovered/healthy again,fever,cough, short breath, OmG I'm going to die - please call 112, O s... this friend died...

**Comment by keeganmcbride** [comment] 2020-03-31 10:28
As we won't add this functionality, closing the issue for now.

**Closed as completed by keeganmcbride** 2020-03-31 10:28 UTC
Labels: data / data visualisation
