### ISSUE TITLE
Pealkiri tahaks parendamist

### ISSUE THREAD

**Issue by henrikaavik** [koroonakaart/koroonakaart#135] opened 2020-07-29 07:54 UTC
Viimase graafiku pealkiir on eksitav

"Positiivsete JA NEGATIIVSETE" testide sooline jaotus. Tegelikult on seal on lihtsalt tehtud testide sooline jaotus, mis võiks olla ka pealkiri, ning nupud, et "kliki ja vaata meeste (või naiste) testide jaotust"

Pealkirjas lubatud positiivsete (ega negatiivsete) testide jaotust meeste ja naiste vahel ei ole selle tabelis üldse.

**Comment by rudotriton** [comment] 2020-08-21 08:17
The last visualization requires the user to click on either gender at which point the visualization changes to show the breakdown of positive and negative tests for just that gender:

<img width="583" alt="gender breakdown" src="https://user-images.githubusercontent.com/14181026/90868503-9823a700-e39f-11ea-8b70-627b748a4940.png">

<img width="577" alt="positive tests" src="https://user-images.githubusercontent.com/14181026/90868544-a376d280-e39f-11ea-9884-2f43eedb8d8b.png">

<img width="579" alt="negative tests" src="https://user-images.githubusercontent.com/14181026/90868573-ad003a80-e39f-11ea-8a1f-f7be72fd86da.png">

**Comment by neuroactive** [comment] 2020-10-30 11:12
I agree with the original poster's point that the title is misleading. A chart should show what is listed in the title without the need to click through for more detail. A different type of visualisation would probably work better here, for example a small multiples approach with two pie charts side by side, which would allow the user to compare the positive and negative tests by gender without the need for the user to make that additional click.

Also, the percentage figure for the tests appears to be rounded to the nearest whole percent, so it is showing the percentage of positive tests as 2% for both men and women. We should increase the precision to one decimal place so that the difference between the percentage of positive tests for men and women can be seen.

**Comment by neuroactive** [comment] 2021-04-13 16:15
Closing this as it's a near duplicate of #135.

**Comment by neuroactive** [comment] 2021-04-13 16:16
Closing this as it's a near duplicate of #128.

**Closed as completed by neuroactive** 2021-04-13 16:16 UTC
