### ISSUE TITLE
Add sorting to pos-neg split by county

### ISSUE THREAD

**Issue by erik-heintare** [koroonakaart/koroonakaart#33] opened 2020-03-22 08:18 UTC
Currently it's not sorted by % or by alphabet, makes harder to read the chart.

**Comment by keeganmcbride** [comment] 2020-03-22 17:44
We sorted alphabetically now.

**Comment by erik-heintare** [comment] 2020-03-23 07:59
"Positiivsed ja negatiivsed testid maakonniti (%)" seems still unsorted

**Comment by jaanus** [comment] 2020-03-23 09:26
Yep, it is super strangely sorted, looks random. It should use the same alphabetic sorting as the rest of county-based info like "Confirmed cases by counties".

Looking at the source, the sort order is defined in two places: `dataPositiveNegativeChart` in `dataConstants.js` for data, and `PositiveNegativeChart.vue` for labels/categories.

I did see that there is a thing that pulls data from Google Sheets and saw the original spreadsheet link, but didn’t identify quickly how does the data from the Sheet get transformed into `dataConstants`. Thus not sure where is the most appropriate place to do the fix.

**Comment by keeganmcbride** [comment] 2020-03-23 09:35
I will do it now. @jaanus The data atm is all hard coded, unforuntately. We are working on pulling it directly from sheets API in the future. This was just due to how data was originally collected and how it is still being made available. All data must still be compiled by hand.

**Comment by keeganmcbride** [comment] 2020-03-23 09:59
Fixed in 9a2a29060111305efe97370160bddecdf8bfa662

**Closed as completed by keeganmcbride** 2020-03-23 09:59 UTC
