### ISSUE TITLE
Bring back distribution of lethal cases by age group

### ISSUE THREAD

**Issue by rams78** [koroonakaart/koroonakaart#204] opened 2021-01-21 07:33 UTC
Trying to hide the fact that there was only 1 lethal case for age group <50 years and the majority of deaths occur for people of age 80+ ?

**Comment by dorkster100** [comment] 2021-01-21 09:19
Please read other related issue before posting such thoughts. Why would an independent organization of volunteers be wanting to hide something?  

Here is an example of an issue that already discussed the issue:
https://github.com/okestonia/koroonakaart/issues/194

**Comment by neuroactive** [comment] 2021-04-13 18:30
Closing this as a duplicate of #127.

**Closed as completed by neuroactive** 2021-04-13 18:30 UTC
