### ISSUE TITLE
Ct value

### ISSUE THREAD

**Issue by Queri1** [koroonakaart/koroonakaart#187] opened 2020-12-17 05:57 UTC
Avalikusta Ct value (keskmine, min, max, mean, normaaljaotus)
vastavalt WHO soovitusele: https://www.who.int/news/item/14-12-2020-who-information-notice-for-ivd-users

**Comment by neuroactive** [comment] 2020-12-20 22:04
I have two main concerns about adding this:

(i) I suspect that most members of the public won't be aware of what a Ct value is and so it would be of little interest to the vast majority of site users.

(ii) I find it extremely unlikely that we would be able to get the required data, especially given that it would need to be collated from different testing providers. I am not even sure whether Terviseamet is tracking information on the Ct value, and it certainly isn't being published as open data at this time.

So unless anyone has any objections I would propose we close this issue.

**Comment by Queri1** [comment] 2020-12-22 03:49
According to the WHO information (https://www.who.int/news/item/14-12-2020-who-information-notice-for-ivd-users) the Ct value is important and should be reported. In this regard, it is possible report also to the public. 
About the awareness of the public. The situation is for everybody, professionals, public, etc. and yes, I assume people are aware of the value.
I am also the aware that the results of the PCR tests are in discussion, also because of the Ct value; and I am also aware that certain people donot want to rise discussion about this subject. 
I assume that the target of the NGO MTÜ Open Knowledge Estonia is to ensure the access of data to the public.  and in this regard the documentation of the Ct value is a measure the public  should be interested in.

**Comment by neuroactive** [comment] 2020-12-22 09:57
According to the following paper published by Public Health England, "Ct values cannot be directly compared between assays of different types – not all laboratories use the same assay, and some may use more than one."

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/926410/Understanding_Cycle_Threshold__Ct__in_SARS-CoV-2_RT-PCR_.pdf

As there are multiple testing laboratories in Estonia, I suspect that they are not all using exactly the same types of device or platform. If that is the case, then it doesn't make sense to publish aggregate statistics about the Ct values. This is probably the reason why, to my knowledge, no countries are publishing open data about how Ct values are changing over time.

Even if it turns out that all the labs do use the same platform, and we decided that we would like to publish that data, I would repeat my earlier point that it's extremely unlikely we would be able to obtain the data in question given that Terviseamet still isn't publishing far more fundamental data such as the numbers and demographic breakdown of those who die because of Covid.

**Comment by Queri1** [comment] 2020-12-22 17:11
We could start a general discussion about the sense of PCR-tests, their usage, the usefulness of the results, etc. But I am not so strong in this subject and I am not able to discuss it with professionals. But I am able, aware and ready to share my knowledge and give my suggestions. On the other side, your task is to inform the public about the real picture. Means to inform about the official opinion as well as the non-official opinion by other professionals. But maybe I am mistaken. 
Also in my understanding, the Terviseamet is collecting info from different sources. also the Teadusnõukogu is collecting and analysis data and report data to the political decision makers. Why not publishing theses data ?  The public interest could and should be to understand the political decisions. 
But sure, if you think it is too much, then it is your choice not to publish data.

**Comment by neuroactive** [comment] 2020-12-23 06:51
> your task is to inform the public about the real picture

We aim to do that. But as I have tried to explain, there are valid technical reasons why Ct values collected from different sources cannot be reported in a combined format such as in averages. It isn't helpful for anyone if we publish data which is scientifically unsound.

> Means to inform about the official opinion as well as the non-official opinion by other professionals.

We have no interest in reporting either the "official" or "unofficial" opinion, we are simply reporting the facts as best we can.

> if you think it is too much, then it is your choice not to publish data.

It isn't a case of it being too much effort, the issue is rather than we cannot publish data which isn't made available to us. Although we can request data from the authorities, we have no control over what data they choose to release. So in many cases when people ask us to publish data, if the data is unavailable then the issue is simply out of our hands.

For the reasons given I am going to close this issue now, but thank you for your suggestion. If there is any other data that you would like to see on the site, then feel free to raise it in a new issue.

**Closed as completed by neuroactive** 2020-12-23 06:51 UTC

**Comment by Queri1** [comment] 2020-12-23 08:24
Thank you for the clear answer.
