### ISSUE TITLE
It would be great to expose distribution of death over age & gender

### ISSUE THREAD

**Issue by SergeiS07** [koroonakaart/koroonakaart#133] opened 2020-06-29 16:16 UTC
Something like existing “Distribution of tests by age and sex”. This is an question often raised....

**Comment by keeganmcbride** [comment] 2020-08-16 18:07
Right now we don't have this data, but if it becomes available we will be more than happy to process and expose it.

**Comment by neuroactive** [comment] 2021-04-13 18:03
Closing as a duplicate of #127.

**Closed as completed by neuroactive** 2021-04-13 18:03 UTC
Labels: backlog
